[deploy]                                                                                                                                                          
releaseCommand = "php artisan migrate --force"
